# Accounts Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: accounts
          image: 167217327829.dkr.ecr.af-south-1.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_PASSWORD
            - name: DB_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_SSLMODE
            - name: DB_SSLROOTCERT
              valueFrom:
                secretKeyRef:
                  name: microservices-db-credentials
                  key: DB_SSLROOTCERT
          volumeMounts:
            - name: rds-cert
              mountPath: /certs
      volumes:
        - name: rds-cert
          hostPath:
            path: /certs
            type: Directory
